#!/bin/sh

if [ -z $XDG_CURRENT_DESKTOP ]; then
    export XDG_CURRENT_DESKTOP="XMonad-GNOME-Flashback:GNOME-Flashback:GNOME"
fi

exec gnome-session --builtin --session=xmonad-gnome-flashback --disable-acceleration-check "$@"
